IO_SENSOR_DATA = 5

SENSOR_RANGE_ACC_G = 4      # unit: g
SENSOR_RANGE_ACC_MS = 5     # unit: m/s^2

FFT_X_IDX = 1
FFT_Y_IDX = 2
FFT_Z_IDX = 4

DATA_IDX_LOGIDX_UTC = 11
DATA_IDX_LOGIDX_UTC_LEN = 9

PARA_LOGIDX_SIZE = 4
PARA_TIME_SIZE = 4